version: '3.8'

services:

  web:
    build: .
    ports:
      - 10000:80
    volumes:
      - ./src:/code/src
      # for rootless docker
      # - /run/user/1000/docker.sock:/var/run/docker.sock

      # non rootless docker
      - /var/run/docker.sock:/var/run/docker.sock
    command:  uvicorn src.api.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis


  worker:
    build: .
    volumes:
      - ./src:/code/src
      # for rootless docker
      # - /run/user/1000/docker.sock:/var/run/docker.sock

      # non rootless docker
      - /var/run/docker.sock:/var/run/docker.sock
    command:  celery -A src.celery.worker worker --loglevel=INFO -E
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BACKUP_VOLUME_NAME=backup_data
      - BACKUP_DIR=/home/rowan/dev/docker-homelab-manager/backup
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
