version: '3.8'

services:

  web:
    build:
      dockerfile: Dockerfile-Dev
    ports:
      - 8000:80
    volumes:
      - ./src:/code/src
      - ./migrations:/code/migrations
      - ./alembic.ini:/code/alembic.ini
      - ${DB_DIR}:/db
      - ${BACKUP_DIR}:/backup

      # for rootless docker
      # - /run/user/1000/docker.sock:/var/run/docker.sock

      # non rootless docker
      - /var/run/docker.sock:/var/run/docker.sock
    #command:  uvicorn src.api:app --host 0.0.0.0 --port 80 --reload --log-config=src/config/log_config.yaml
    # run this when there is a database table change
    command: "sh -c 'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80 --reload --reload-dir src --reload-exclude *__pycache__* --log-config=src/config/log_config.yaml'"
    environment:
      - APSCHEDULE_JOBSTORE_URL=sqlite:////db/scheduler.db
      - DATABASE_URL=sqlite:////db/database.db
      - TZ=Pacific/Auckland
      - BACKUP_DIR=${BACKUP_DIR}
