version: '3.8'

services:

  web:
    build: 
      dockerfile: Dockerfile-Dev
    ports:
      - 10000:80
    volumes:
      - ./src:/code/src
      - ${DB_DIR}:/db

      # for rootless docker
      # - /run/user/1000/docker.sock:/var/run/docker.sock

      # non rootless docker
      - /var/run/docker.sock:/var/run/docker.sock
    command:  uvicorn src.api.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis


  worker:
    build: 
      dockerfile: Dockerfile-Dev
    volumes:
      - ./src:/code/src
      - ${BACKUP_DIR}:/backup
      - ${DB_DIR}:/db
      # for rootless docker
      # - /run/user/1000/docker.sock:/var/run/docker.sock

      # non rootless docker
      - /var/run/docker.sock:/var/run/docker.sock
    command:  watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A src.celery.worker worker --loglevel=INFO -E
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BACKUP_DIR=${BACKUP_DIR}
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
