version: '3.8'

services:

  web:
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ${DB_DIR}:/db
      - ${BACKUP_DIR}:/backup

      # for rootless docker
      # - /run/user/1000/docker.sock:/var/run/docker.sock

      # non rootless docker
      - /var/run/docker.sock:/var/run/docker.sock
    command:  fastapi run src/main.py --host 0.0.0.0 --port 80
    # run this when there is a database table change
    #command: "sh -c 'alembic upgrade head && uvicorn src.api:app --host 0.0.0.0 --port 80
    environment:
      - APSCHEDULE_JOBSTORE_URL=sqlite:////db/scheduler.db
      - DATABASE_URL=sqlite:////db/database.db
      - TZ=Pacific/Auckland
      - BACKUP_DIR=${BACKUP_DIR}
