"""new remote path field sftp_source

Revision ID: 2123d3770f00
Revises: 264a10d3ad32
Create Date: 2024-08-14 21:49:53.440720

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2123d3770f00'
down_revision: Union[str, None] = '264a10d3ad32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sftpbackupsource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sftpbackupsource', schema=None) as batch_op:
        batch_op.drop_column('remote_path')

    # ### end Alembic commands ###
