"""new source table

Revision ID: 264a10d3ad32
Revises: c5a3fa8f56c6
Create Date: 2024-08-12 22:01:11.630974

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264a10d3ad32'
down_revision: Union[str, None] = 'c5a3fa8f56c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sftpbackupsource',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ssh_key_type', sa.Enum('RSA', 'ED25519', 'ECDSA', 'DSA', name='sshkeytypes'), nullable=True),
    sa.Column('ssh_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sftpbackupsource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sftpbackupsource_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_sftpbackupsource_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sftpbackupsource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sftpbackupsource_name'))
        batch_op.drop_index(batch_op.f('ix_sftpbackupsource_hostname'))

    op.drop_table('sftpbackupsource')
    # ### end Alembic commands ###
