"""add unkown job table

Revision ID: 27fb915c6d03
Revises: c5a3fa8f56c6
Create Date: 2024-03-22 15:51:48.692225

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fb915c6d03'
down_revision: Union[str, None] = 'c5a3fa8f56c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unknownloadingjob',
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unknownloadingjob')
    # ### end Alembic commands ###
