"""remove succesful

Revision ID: 4ca112e04efd
Revises: 9724dd6f04cf
Create Date: 2024-08-27 22:20:46.421632

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ca112e04efd"
down_revision: Union[str, None] = "9724dd6f04cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.drop_column("successful")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("successful", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
