"""inital-seed

Revision ID: 677098e97ac3
Revises: 
Create Date: 2024-02-10 22:01:25.253309

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "677098e97ac3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("backup_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schedule_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backup_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("volume_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backup_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backup_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backup_created", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("backup_id"),
    )
    op.create_table(
        "errorbackups",
        sa.Column("backup_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("backup_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("backup_id"),
    )
    op.create_table(
        "errorrestoredbackups",
        sa.Column("restore_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("restore_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("restore_id"),
    )
    op.create_table(
        "restoredbackups",
        sa.Column("restore_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("restore_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("volume_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backup_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("restored_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("restore_id"),
    )
    op.create_table(
        "backupfilenames",
        sa.Column(
            "backup_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("backup_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backups.backup_id"],
        ),
        sa.PrimaryKeyConstraint("backup_filename"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backupfilenames")
    op.drop_table("restoredbackups")
    op.drop_table("errorrestoredbackups")
    op.drop_table("errorbackups")
    op.drop_table("backups")
    # ### end Alembic commands ###
