"""remove old error and success fields

Revision ID: 866892f8fecb
Revises: 7c64154a5d29
Create Date: 2024-02-07 18:19:55.640409

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866892f8fecb'
down_revision: Union[str, None] = '7c64154a5d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 'errorMessage')
    op.drop_column('backups', 'success')
    op.drop_column('restoredbackups', 'errorMessage')
    op.drop_column('restoredbackups', 'success')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restoredbackups', sa.Column('success', sa.BOOLEAN(), nullable=True))
    op.add_column('restoredbackups', sa.Column('errorMessage', sa.VARCHAR(), nullable=True))
    op.add_column('backups', sa.Column('success', sa.BOOLEAN(), nullable=True))
    op.add_column('backups', sa.Column('errorMessage', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
