"""Added backup table

Revision ID: 94bef540a56e
Revises: 
Create Date: 2024-02-03 15:24:55.551499

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94bef540a56e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("backup_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("backup_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("backup_created", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("volume_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("restored", sa.Boolean(), nullable=True),
        sa.Column("restored_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("backup_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backups")
    # ### end Alembic commands ###
