"""new backup status field

Revision ID: 9724dd6f04cf
Revises: 2123d3770f00
Create Date: 2024-08-19 20:29:35.812921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9724dd6f04cf"
down_revision: Union[str, None] = "2123d3770f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backups", schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "Created", "InProgress", "Processed", "Errored", name="backupstatus"
                ),
            )
        )
    op.execute("UPDATE backups SET status = 'Processed' WHERE successful = 1")
    op.execute("UPDATE backups SET status = 'Errored' WHERE successful = 0")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
