"""db refine

Revision ID: b8b1e311a69a
Revises: 
Create Date: 2024-02-04 15:06:39.137150

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b1e311a69a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('backup_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backup_file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backup_created', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('backup_id')
    )
    op.create_index(op.f('ix_backups_backup_file_name'), 'backups', ['backup_file_name'], unique=False)
    op.create_table('schedulebackups',
    sa.Column('schedule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backup_file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crontab', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_id', 'backup_file_name')
    )
    op.create_table('restoredbackups',
    sa.Column('restore_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backup_file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_file_name_schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('volume_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restored_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('errorMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['backup_file_name'], ['backups.backup_file_name'], ),
    sa.ForeignKeyConstraint(['backup_file_name_schedule'], ['schedulebackups.backup_file_name'], ),
    sa.PrimaryKeyConstraint('restore_id')
    )
    op.create_index(op.f('ix_restoredbackups_backup_file_name'), 'restoredbackups', ['backup_file_name'], unique=False)
    op.create_index(op.f('ix_restoredbackups_backup_file_name_schedule'), 'restoredbackups', ['backup_file_name_schedule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restoredbackups_backup_file_name_schedule'), table_name='restoredbackups')
    op.drop_index(op.f('ix_restoredbackups_backup_file_name'), table_name='restoredbackups')
    op.drop_table('restoredbackups')
    op.drop_table('schedulebackups')
    op.drop_index(op.f('ix_backups_backup_file_name'), table_name='backups')
    op.drop_table('backups')
    # ### end Alembic commands ###
