"""backup status field

Revision ID: c68056707d86
Revises: 2123d3770f00
Create Date: 2024-08-18 19:41:55.557045

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68056707d86'
down_revision: Union[str, None] = '2123d3770f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Created', 'InProgress', 'Processed', 'Errored', name='backupstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
