name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        registry: ghcr.io
        githubOrg: mrllama123 # optional
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        addLatest: true
